BILLING_SERVICE_READ = "billing.service.read"
BILLING_SERVICE_WRITE = "billing.service.write"
BILLING_CHARGE_WRITE = "billing.charge.write"
BILLING_INVOICE_READ = "billing.invoice.read"
BILLING_INVOICE_WRITE = "billing.invoice.write"
BILLING_PAYMENT_WRITE = "billing.payment.write"
