export type WorkspaceId = "operations"|"people"|"connect"|"finance"|"public-health"|"compliance"|"resilience"|"intelligence";
export type WorkspaceDefinition = {id:WorkspaceId;label:string;icon:string;description:string;links:readonly [string,string][]};
export const WORKSPACES:readonly WorkspaceDefinition[]=[
{id:"operations",label:"Operations",icon:"🏥",description:"Run the facility and coordinate care.",links:[["/","Dashboard"],["/appointments","Appointments"],["/queue","Clinical queue"],["/clinical-worklist","Clinical worklist"],["/encounters","Encounters"],["/laboratory","Laboratory"],["/pharmacy","Pharmacy"],["/mch","Maternal & child health"],["/billing","Billing"],["/reports","Reports"]]},
{id:"people",label:"People",icon:"👥",description:"Patients, families, care journeys and communication.",links:[["/patients","Patient register"],["/patients/new","Register patient"],["/household-wallet","Household health wallet"],["/messages","Messages"],["/referrals","Referrals"],["/care-coordination","Care coordination"]]},
{id:"connect",label:"Connect",icon:"🔗",description:"Exchange health information across authorized systems.",links:[["/interoperability","Health exchange"],["/interoperability/clinical","Clinical interoperability"],["/health-exchange","National health exchange"],["/universal-identity","Universal identity"],["/national-identity","National identity"],["/referral-routing","Intelligent referral routing"],["/referral-booking","Referral decision & booking"]]},
{id:"finance",label:"Finance",icon:"💰",description:"Coverage, claims, payer operations and cash.",links:[["/claims","Claims & rework"],["/claims-clearinghouse","Claims clearinghouse"],["/coverage/sha-eligibility","Coverage verification"],["/financial-command-centre","Financial command centre"],["/payer-command","Payer command centre"],["/revenue-control-tower","Revenue control tower"],["/revenue-cash-assurance","Revenue & cash assurance"],["/collection-work","Collection work"],["/revenue-recovery","Revenue recovery"],["/denial-appeals","Denial & appeals"],["/contract-guardrails","Contract guardrails"],["/contract-execution","Contract execution"]]},
{id:"public-health",label:"Public Health",icon:"🌍",description:"Surveillance, reporting, population and network health.",links:[["/national-command-centre","Health command centre"],["/national-intelligence","National intelligence"],["/national-facilities","Facility network"],["/national/referrals","Referral network"],["/national/capacity","Clinical capacity"],["/national-supply","Medicine supply"],["/national/supply/planning","Supply planning"],["/reports","Health reporting"]]},
{id:"compliance",label:"Compliance",icon:"🛡",description:"Security, privacy, governance and readiness.",links:[["/security-operations","Security operations"],["/tenancy","Organizations & tenancy"],["/certification","DHA certification"],["/retention","Retention & erasure"],["/risk-register","Residual risk register"],["/change-control","Change control"],["/national-readiness","National readiness"],["/production","Production readiness"]]},
{id:"resilience",label:"Resilience",icon:"📡",description:"Keep care running through outages and recovery events.",links:[["/business-continuity","Business continuity"],["/offline-clinic","Offline clinic"],["/continuity-scan","Continuity verification"],["/disaster-recovery","Disaster recovery"],["/observability","Observability & SLOs"],["/performance","Performance acceptance"],["/integrations","Integration operations"]]},
{id:"intelligence",label:"Intelligence",icon:"📊",description:"Turn operational data into governed decisions.",links:[["/product-readiness","National product readiness"],["/command-centre","Command centre"],["/warehouse","Analytics warehouse"],["/national-intelligence","National intelligence"],["/executive-revenue","Executive revenue"],["/revenue-action-priorities","Revenue action priorities"],["/recovery-cash-conversion","Recovery & cash conversion"],["/coverage-simulator","Coverage simulator"]]}
];
