import {useEffect,useMemo,useRef,useState} from "react";
import {useNavigate} from "react-router-dom";
import {WORKSPACES} from "../workspaces/workspaces";

type Result={label:string;path:string;workspace:string;hint:string};

export function GlobalCommand(){
 const navigate=useNavigate(); const [open,setOpen]=useState(false); const [q,setQ]=useState(""); const ref=useRef<HTMLInputElement>(null);
 const results=useMemo<Result[]>(()=>{const term=q.trim().toLowerCase(); if(!term)return WORKSPACES.flatMap(w=>w.links.slice(0,2).map(([path,label])=>({label,path,workspace:w.label,hint:"Workspace module"}))).slice(0,8); return WORKSPACES.flatMap(w=>w.links.map(([path,label])=>({label,path,workspace:w.label,hint:"Module"}))).filter(x=>(x.label+" "+x.path+" "+x.workspace).toLowerCase().includes(term)).slice(0,10)},[q]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setOpen(true);setTimeout(()=>ref.current?.focus(),0)} if(e.key==="Escape")setOpen(false)};window.addEventListener("keydown",fn);return()=>window.removeEventListener("keydown",fn)},[]);
 return <><button type="button" aria-label="Open command search" onClick={()=>{setOpen(true);setTimeout(()=>ref.current?.focus(),0)}} style={{position:"fixed",right:22,top:14,zIndex:30,border:"1px solid rgba(148,163,184,.35)",borderRadius:10,padding:"8px 12px",background:"rgba(255,255,255,.94)",cursor:"pointer"}}>⌘K Search</button>{open&&<div role="dialog" aria-modal="true" onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,zIndex:40,background:"rgba(15,23,42,.45)",display:"flex",justifyContent:"center",alignItems:"flex-start",paddingTop:"10vh"}}><div onClick={e=>e.stopPropagation()} style={{width:"min(680px,92vw)",background:"#fff",borderRadius:14,boxShadow:"0 20px 60px rgba(0,0,0,.25)",overflow:"hidden"}}><input ref={ref} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search AfyaSync modules and workspaces…" style={{width:"100%",boxSizing:"border-box",padding:"18px",fontSize:17,border:0,borderBottom:"1px solid #e2e8f0",outline:"none"}}/>{results.map(r=><button key={r.path+r.label} type="button" onClick={()=>{setOpen(false);navigate(r.path)}} style={{display:"block",width:"100%",textAlign:"left",padding:"13px 18px",border:0,borderBottom:"1px solid #f1f5f9",background:"#fff",cursor:"pointer"}}><strong>{r.label}</strong><span style={{display:"block",fontSize:12,opacity:.65}}>{r.workspace} · {r.hint}</span></button>)}{!results.length&&<div style={{padding:20}}>No matching authorized module found.</div>}<div style={{padding:"9px 18px",fontSize:12,opacity:.6}}>Ctrl/Cmd + K to open · Esc to close</div></div></div>}</>
}