import { NavLink, Outlet } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";

type NavLinkItem = readonly [string, string];
type NavGroup = { label: string; links: readonly NavLinkItem[] };

const navGroups: readonly NavGroup[] = [
  { label: "Overview", links: [["/", "Dashboard"], ["/command-centre", "Command centre"], ["/national-command-centre", "National command centre"], ["/national-intelligence", "National intelligence"], ["/national-identity", "National identity"], ["/national-facilities", "Facility network"], ["/national-staff", "Staff network"], ["/national-payers", "Payer network"], ["/national-benefits", "Benefit configuration"], ["/national-supply", "Medicine supply"], ["/national/supply/planning", "Supply planning"], ["/national/referrals", "Referral network"], ["/national/capacity", "Clinical capacity"], ["/coverage-simulator", "Coverage simulator"]] },
  { label: "Patients & care", links: [["/patients", "Patient register"], ["/household-wallet", "Household health wallet"], ["/patients/new", "Register patient"], ["/patients/sha-lookup", "Coverage lookup"], ["/continuity-scan", "Continuity card scan"], ["/offline-clinic", "Offline clinic"], ["/coverage/sha-eligibility", "SHA eligibility verification"], ["/appointments", "Appointments"], ["/messages", "Messages"], ["/treat-abroad", "Treat Abroad"], ["/queue", "Clinical queue"], ["/referrals", "Referrals"]] },
  { label: "Clinical services", links: [["/mch", "Maternal & child health"], ["/laboratory", "Laboratory"], ["/pharmacy", "Pharmacy"], ["/benefits", "Benefit packages"]] },
  { label: "Revenue & reporting", links: [["/billing", "Billing"], ["/claims", "Claims & rework"], ["/reports", "Daily & monthly reports"], ["/integrations", "Integration operations"], ["/security-operations", "Security operations"], ["/workforce", "Workforce & credentials"], ["/onboarding", "Onboarding & migration"], ["/training", "Training & help"], ["/rollout", "County rollout & evidence"], ["/warehouse", "Analytics warehouse"], ["/certification", "DHA certification"], ["/production", "Production readiness"], ["/observability", "Observability & SLOs"], ["/retention", "Retention & erasure"], ["/partner-sandbox", "Partner sandbox"]] },
] as const;

const KENYA_CREST = "https://upload.wikimedia.org/wikipedia/commons/f/f6/Coat_of_arms_of_Kenya_%28Official%29.svg";
function KenyaCrest({ className = "" }: { className?: string }) { return <img className={`kenya-crest ${className}`} src={KENYA_CREST} alt="Coat of arms of Kenya" />; }

export function Layout() {
  const auth = useAuth();
  return <div className="app-shell"><aside className="sidebar" aria-label="Primary navigation"><div className="brand brand-row"><div className="brand-mark"><KenyaCrest /></div><div className="brand-copy"><strong>AfyaSync</strong><span>National health platform</span></div></div><div className="institution-strip"><span>KENYA</span><strong>Healthcare, connected.</strong></div><div className="facility-context"><span className="facility-context-label">CURRENT FACILITY</span><strong>{auth.facilityName || "No facility selected"}</strong></div><nav>{navGroups.map(group => <div className="nav-group" key={group.label}><div className="nav-section">{group.label}</div>{group.links.map(([to, label]) => <NavLink key={to} to={to} end={to === "/"}><span className="nav-dot" aria-hidden="true" />{label}</NavLink>)}</div>)}</nav><div className="sidebar-footer"><div className="user-context"><span className="user-avatar" aria-hidden="true">{(auth.username || "U").slice(0, 1).toUpperCase()}</span><div><strong>{auth.username || "Staff user"}</strong><span className="muted small">Authenticated staff</span></div></div><button type="button" className="linkish signout" onClick={() => void auth.logout()}>Sign out</button></div></aside><main className="content"><header className="topbar"><div className="topbar-brand"><KenyaCrest className="topbar-crest" /><div><span className="topbar-kicker">REPUBLIC OF KENYA • HEALTHCARE OPERATIONS</span><span className="topbar-title">AfyaSync</span></div></div><div className="topbar-context"><span className="status-dot" /> <span>{auth.facilityName || "Facility workspace"}</span></div></header><div className="content-inner"><Outlet /></div><footer className="site-footer"><div className="footer-main"><div className="footer-identity"><KenyaCrest className="footer-crest" /><div><strong>AfyaSync</strong><span>Healthcare, connected.</span><small>Kenya health information infrastructure</small></div></div><div className="footer-links"><strong>PLATFORM</strong><span>Secure health operations</span><span>Interoperable services</span><span>Patient-centred care</span></div><div className="footer-links"><strong>GOVERNANCE</strong><span>Authorised users only</span><span>Audit-ready operations</span><span>Privacy & security by design</span></div></div><div className="footer-bottom"><div className="footer-copyright">
  <span>© {new Date().getFullYear()} AfyaSync. Developed by <strong>BAHATI GAD WANGWE</strong>. All rights reserved.</span>
  <span>Unauthorized copying, reverse engineering, redistribution or commercial use is strictly prohibited and will be prosecuted under Kenyan and international law.</span>
  <span>AfyaSync is an independent health technology platform and is not the Government of Kenya.</span>
</div></div></footer></main></div>;
}
