import { useEffect, useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { api, ApiError } from "../api/client";

type Service={id:string;code:string;name:string;service_type:string;price:number;status:string}; type Invoice={id:string;invoice_id:string;patient_id:string;encounter_id:string;total_amount:number;patient_amount:number;payer_amount:number;status:string};
const money=(n:number|string)=>`KES ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`; const transactionKey=()=>`WEB-${crypto.randomUUID()}`;
export function BillingPage(){
 const [params]=useSearchParams(); const [services,setServices]=useState<Service[]>([]); const [invoices,setInvoices]=useState<Invoice[]>([]); const [patients,setPatients]=useState<any[]>([]); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const [invoiceId,setInvoiceId]=useState(""); const [patientId,setPatientId]=useState(params.get("patientId")||""); const [encounterId,setEncounterId]=useState(params.get("encounterId")||""); const [svc,setSvc]=useState({code:"",name:"",service_type:"CONSULTATION",price:""}); const [pay,setPay]=useState({invoice_id:"",amount:"",payment_method:"CASH",provider:"",external_reference:""});
 async function load(){setLoading(true);setError(null);try{const [s,i,p]=await Promise.all([api.listBillingServices(),api.listInvoices(),api.listPatients(200,0)]);setServices(s);setInvoices(i);setPatients(p.items);}catch(e){setError(e instanceof ApiError?e.code:"BILLING_LOAD_FAILED")}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
 async function createInvoice(){if(!encounterId){setError("SELECT_ENCOUNTER_FROM_PATIENT_JOURNEY");return}setBusy(true);setError(null);try{const i=await api.createInvoice(encounterId);setMessage(`Invoice ${i.invoice_id} created.`);setInvoiceId(i.id);await load()}catch(e){setError(e instanceof ApiError?e.code:"INVOICE_CREATE_FAILED")}finally{setBusy(false)}}
 async function onAddService(e:FormEvent){e.preventDefault();setBusy(true);try{await api.createBillingService({code:svc.code.trim().toUpperCase(),name:svc.name.trim(),service_type:svc.service_type,price:Number(svc.price)});setSvc({code:"",name:"",service_type:"CONSULTATION",price:""});await load()}catch(e){setError(e instanceof ApiError?e.code:"SERVICE_CREATE_FAILED")}finally{setBusy(false)}}
 async function onPay(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{await api.recordPayment({invoice_id:pay.invoice_id,amount:Number(pay.amount),payment_method:pay.payment_method,provider:pay.provider.trim()||null,external_reference:pay.external_reference.trim()||null},transactionKey());setMessage("Payment recorded and linked to the invoice.");setPay({invoice_id:"",amount:"",payment_method:"CASH",provider:"",external_reference:""});await load()}catch(e){setError(e instanceof ApiError?e.code:"PAYMENT_FAILED")}finally{setBusy(false)}}
 const selected=invoices.find(i=>i.id===pay.invoice_id); const pname=(id:string)=>{const p=patients.find(x=>x.id===id);return p?[p.first_name,p.middle_name,p.last_name].filter(Boolean).join(" "):id};
 return <section className="page-stack"><header className="page-heading"><div><p className="eyebrow">Financial workflow</p><h1>Billing</h1><p className="muted">Receive the named patient, create the encounter invoice, record payment, then return the same patient to the clinical journey.</p></div><button type="button" className="button secondary" onClick={()=>void load()}>Refresh</button></header>{error&&<div className="error">{error}</div>}{message&&<div className="success-box">{message}</div>}
 {patientId&&<article className="card"><p className="eyebrow">Patient at billing</p><h2>{pname(patientId)}</h2><p className="muted">Afya ID: {patients.find(p=>p.id===patientId)?.afya_id||"—"} · Encounter: {encounterId||"Select from journey"}</p><div className="actions"><Link className="button secondary" to={`/patients/${patientId}/journey`}>Open care journey</Link>{encounterId&&<button type="button" onClick={()=>void createInvoice()} disabled={busy}>Create / refresh invoice</button>}</div></article>}
 {loading?<p>Loading billing…</p>:<><article className="card"><h2>Services ({services.length})</h2><form className="form-grid" onSubmit={onAddService}><label>Code<input required value={svc.code} onChange={e=>setSvc({...svc,code:e.target.value})}/></label><label>Name<input required value={svc.name} onChange={e=>setSvc({...svc,name:e.target.value})}/></label><label>Type<select value={svc.service_type} onChange={e=>setSvc({...svc,service_type:e.target.value})}><option>CONSULTATION</option><option>LAB</option><option>PHARMACY</option><option>PROCEDURE</option><option>OTHER</option></select></label><label>Price (KES)<input required type="number" min="0.01" step="0.01" value={svc.price} onChange={e=>setSvc({...svc,price:e.target.value})}/></label><div className="full actions"><button disabled={busy}>Create service</button></div></form><div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Type</th><th>Price</th><th>Status</th></tr></thead><tbody>{services.map(s=><tr key={s.id}><td>{s.code}</td><td>{s.name}</td><td>{s.service_type}</td><td>{money(s.price)}</td><td>{s.status}</td></tr>)}</tbody></table></div></article>
 <article className="card"><h2>Invoices ({invoices.length})</h2><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Patient</th><th>Encounter</th><th>Total</th><th>Patient due</th><th>Payer</th><th>Status</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.invoice_id}</td><td><Link to={`/patients/${i.patient_id}/journey`}><strong>{pname(i.patient_id)}</strong></Link></td><td>{i.encounter_id}</td><td>{money(i.total_amount)}</td><td>{money(i.patient_amount)}</td><td>{money(i.payer_amount)}</td><td><span className="status-pill">{i.status}</span></td></tr>)}</tbody></table></div></article>
 <article className="card"><h2>Record payment</h2><p className="muted">Select a real invoice. Confirmed payments are persisted against that invoice and can be used by downstream workflow gates.</p><form className="form-grid" onSubmit={onPay}><label className="full">Invoice<select required value={pay.invoice_id} onChange={e=>setPay({...pay,invoice_id:e.target.value})}><option value="">Select invoice</option>{invoices.filter(i=>i.status!=="PAID").map(i=><option key={i.id} value={i.id}>{i.invoice_id} · {pname(i.patient_id)} · {money(i.patient_amount)} due</option>)}</select></label><label>Amount<input required type="number" min="0.01" max={selected?.patient_amount} step="0.01" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})}/></label><label>Method<select value={pay.payment_method} onChange={e=>setPay({...pay,payment_method:e.target.value,provider:"",external_reference:""})}><option>CASH</option><option>MPESA</option><option>CARD</option><option>BANK</option></select></label>{pay.payment_method!=="CASH"&&<><label>Provider<input required value={pay.provider} onChange={e=>setPay({...pay,provider:e.target.value})}/></label><label>External reference<input required value={pay.external_reference} onChange={e=>setPay({...pay,external_reference:e.target.value})}/></label></>}<div className="full actions"><button disabled={busy||!pay.invoice_id}>{busy?"Posting…":"Record payment"}</button></div></form></article></>}</section>;
}
