import {useEffect,useState} from "react";
import {api} from "../api/client";
export function CareCoordinationPage(){
 const [o,setO]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[referral,setReferral]=useState(""),[due,setDue]=useState(""),[notes,setNotes]=useState(""),[status,setStatus]=useState(""),[msg,setMsg]=useState(""),[error,setError]=useState("");
 async function load(){try{const [a,b]=await Promise.all([api.careCoordinationOverview(),api.careCoordinationCases(status||undefined)]);setO(a);setRows(b)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[status]);
 async function create(){setError("");setMsg("");try{await api.careCoordinationCreate({referral_id:referral,due_at:due?new Date(due).toISOString():undefined,notes:notes||undefined});setMsg("Care coordination case created.");setReferral("");setNotes("");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function update(id:string,next:string){try{await api.careCoordinationUpdate(id,{status:next});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 return <section className="page-stack">
 <header className="page-heading"><div><p className="eyebrow">Phase 51 · National care coordination</p><h1>Care coordination exchange</h1><p className="muted">Turn a referral into a tracked care journey: acceptance, scheduling, handoff, completion and overdue follow-up.</p></div><button className="button secondary" onClick={()=>void load()}>Refresh</button></header>
 {error&&<div className="error-banner">{error}</div>}{msg&&<div className="notice-box">{msg}</div>}
 {o&&<div className="metrics-grid"><article className="card metric-card"><span className="muted">Cases</span><strong>{o.total}</strong></article><article className="card metric-card"><span className="muted">Open</span><strong>{o.open}</strong></article><article className="card metric-card"><span className="muted">Overdue</span><strong>{o.overdue}</strong></article><article className="card metric-card"><span className="muted">Completed</span><strong>{o.completed}</strong></article></div>}
 <article className="card"><div className="card-header"><div><h2>Create coordination case</h2><p className="muted">Link one operational coordination case to an existing referral.</p></div></div><div className="filter-row"><label>Referral UUID<input value={referral} onChange={e=>setReferral(e.target.value)} /></label><label>Due at<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} /></label><label>Notes<input value={notes} onChange={e=>setNotes(e.target.value)} /></label><button className="button filter-action" onClick={()=>void create()} disabled={!referral}>Create case</button></div></article>
 <article className="card"><div className="card-header"><div><h2>Coordination queue</h2><p className="muted">Patient IDs are not displayed in this national operational queue.</p></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>OPEN</option><option>ACCEPTED</option><option>SCHEDULED</option><option>HANDED_OFF</option><option>COMPLETED</option><option>OVERDUE</option><option>CANCELLED</option></select></div>
 <div className="table-wrap"><table><thead><tr><th>Case</th><th>Referral</th><th>Route</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.case_number}</strong></td><td>{x.referral_id}</td><td>{x.source_facility_id} → {x.destination_facility_id}</td><td>{x.due_at?new Date(x.due_at).toLocaleString("en-KE"):"—"}</td><td><span className="status-pill">{x.status}</span></td><td>{x.status==="OPEN"&&<button className="button secondary" onClick={()=>void update(x.id,"ACCEPTED")}>Accept</button>}{x.status==="ACCEPTED"&&<button className="button secondary" onClick={()=>void update(x.id,"SCHEDULED")}>Schedule</button>}{x.status==="SCHEDULED"&&<button className="button secondary" onClick={()=>void update(x.id,"HANDED_OFF")}>Handoff</button>}{x.status==="HANDED_OFF"&&<button className="button secondary" onClick={()=>void update(x.id,"COMPLETED")}>Complete</button>}</td></tr>)}</tbody></table></div></article>
 <div className="info-box"><strong>Design:</strong> this coordination layer sits above the existing referral and HIE capabilities. It tracks whether the patient actually moves through the care pathway instead of treating a sent referral as a completed outcome.</div>
 </section>
}