import {useEffect,useState} from "react";
import {api} from "../api/client";

export function ClaimsClearinghousePage(){
 const [o,setO]=useState<any>(null),[cases,setCases]=useState<any[]>([]),[claimId,setClaimId]=useState(""),[key,setKey]=useState(""),[source,setSource]=useState("SHA"),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){try{const [a,b]=await Promise.all([api.claimsClearinghouseOverview(),api.claimsClearinghouseCases()]);setO(a);setCases(b);setError("")}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[]);
 async function intake(){try{await api.claimsClearinghouseIntake({claim_id:claimId,idempotency_key:key});setMessage("Claim accepted into the universal clearinghouse.");setClaimId("");setKey("");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function validate(id:string){try{await api.claimsClearinghouseValidate(id);setMessage("Case validated.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function submit(id:string){try{await api.claimsClearinghouseSubmit(id);setMessage("Case queued for the configured payer adapter.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 return <section className="page-stack">
  <div className="page-header"><div><p className="eyebrow">Phase 57 · Universal financing infrastructure</p><h1>Universal Claims Clearinghouse</h1><p className="muted">One normalized claims pipeline for SHA, private insurers, employer schemes, county programs and self-pay workflows.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div>
  {error&&<div className="error-banner">{error}</div>}{message&&<div className="notice-box">{message}</div>}
  {o&&<div className="stat-grid"><div className="stat-card"><span>Cases</span><strong>{o.cases}</strong><small>Normalized clearinghouse cases</small></div><div className="stat-card"><span>Claim value</span><strong>KES {Number(o.claim_amount).toLocaleString()}</strong><small>Gross routed value</small></div><div className="stat-card"><span>Approved</span><strong>KES {Number(o.approved_amount).toLocaleString()}</strong><small>Payer-approved value</small></div><div className="stat-card"><span>Paid</span><strong>KES {Number(o.paid_amount).toLocaleString()}</strong><small>Recorded remittances</small></div></div>}
  <section className="card"><h2>Normalize a claim</h2><div className="form-grid"><label>Claim UUID<input value={claimId} onChange={e=>setClaimId(e.target.value)} placeholder="Existing claim UUID"/></label><label>Idempotency key<input value={key} onChange={e=>setKey(e.target.value)} placeholder="Unique submission key"/></label><label>Expected source<select value={source} onChange={e=>setSource(e.target.value)}><option>SHA</option><option>PRIVATE_INSURER</option><option>EMPLOYER_SCHEME</option><option>COUNTY_PROGRAM</option><option>SELF_PAY</option></select></label></div><button onClick={()=>void intake()}>Send to clearinghouse</button><p className="muted">Source is normalized from payer data; the selector is informational for operators.</p></section>
  <section className="card"><h2>Clearinghouse work queue</h2><div className="table-wrap"><table><thead><tr><th>Case</th><th>Source</th><th>Adapter</th><th>Status</th><th>Claim</th><th>Approved</th><th>Paid</th><th>Actions</th></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td>{c.case_number}</td><td>{c.source_type}</td><td>{c.adapter_code||"Not configured"}</td><td>{c.status}</td><td>KES {Number(c.claim_amount).toLocaleString()}</td><td>KES {Number(c.approved_amount).toLocaleString()}</td><td>KES {Number(c.paid_amount).toLocaleString()}</td><td><div className="button-row">{["INTAKE","VALIDATING","FAILED","REJECTED"].includes(c.status)&&<button onClick={()=>void validate(c.id)}>Validate</button>}{c.status==="READY"&&<button onClick={()=>void submit(c.id)}>Submit</button>}{["SUBMITTED","ACKNOWLEDGED","IN_REVIEW"].includes(c.status)&&<button onClick={()=>void api.claimsClearinghouseEvents(c.id).then(e=>setMessage(`${e.length} lifecycle events recorded.`))}>History</button>}</div></td></tr>)}</tbody></table></div></section>
 </section>
}
