import {useEffect,useState} from "react";
import {api} from "../api/client";
export default function ContractRenewalPage(){
 const[days,setDays]=useState(180),[data,setData]=useState<any>({contracts:[],actions:[]}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const token=localStorage.getItem("access_token");const base=import.meta.env.VITE_API_URL||"";const r=await fetch(base+"/api/v1/contract-renewal?days="+days,{headers:token?{Authorization:"Bearer "+token}:{}});if(!r.ok)throw new Error("Unable to load contract renewal intelligence");setData(await r.json())}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[days]);
 return <div className="page"><div className="page-header"><div><h1>Contract Renewal Intelligence</h1><p>Evidence-based renewal preparation using contract, reimbursement, denial and recovery performance.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={90}>90 days</option><option value={180}>180 days</option><option value={365}>365 days</option></select></div>
 {error&&<div className="alert">{error}</div>}{loading?<div className="card">Loading…</div>:<>
 <div className="grid grid-3"><div className="card"><strong>{data.contracts?.length||0}</strong><span>Contracts</span></div><div className="card"><strong>{data.actions?.length||0}</strong><span>Review actions</span></div><div className="card"><strong>KES {((data.contracts||[]).reduce((s:any,x:any)=>s+(x.recovery_outstanding||0),0)).toLocaleString()}</strong><span>Recovery exposure</span></div></div>
 <section className="card"><h2>Contract performance</h2><div className="table-wrap"><table><thead><tr><th>Contract</th><th>Payer</th><th>Status</th><th>Renewal</th><th>Claims</th><th>Denial</th><th>Collection</th><th>Recovery</th></tr></thead><tbody>{(data.contracts||[]).map((x:any)=><tr key={x.contract_id}><td>{x.contract_reference}</td><td>{x.payer_name}</td><td>{x.status}</td><td>{x.renewal_due_at?new Date(x.renewal_due_at).toLocaleDateString():"—"}</td><td>{x.claims_180d}</td><td>{x.denial_rate_180d}%</td><td>{x.collection_rate_180d}%</td><td>KES {x.recovery_outstanding.toLocaleString()}</td></tr>)}</tbody></table></div></section>
 <section className="card"><h2>Renewal review queue</h2><div className="table-wrap"><table><thead><tr><th>Priority</th><th>Payer</th><th>Action</th><th>Evidence</th></tr></thead><tbody>{(data.actions||[]).map((x:any,i:number)=><tr key={i}><td>{x.priority}</td><td>{x.payer_name}</td><td><strong>{x.action}</strong></td><td>{x.reason}</td></tr>)}</tbody></table></div></section></>}</div>
}