import { useCallback,useEffect,useState } from "react";
import type { FormEvent } from "react";
import { api } from "../api/client";
export function DisasterRecoveryPage(){
 const [posture,setPosture]=useState<any>({}),[checklist,setChecklist]=useState<any>({}),[backups,setBackups]=useState<any[]>([]),[drills,setDrills]=useState<any[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const [source,setSource]=useState("POSTGRES"),[backupStatus,setBackupStatus]=useState("RECORDED"),[detail,setDetail]=useState("");
 const [type,setType]=useState("TABLETOP"),[scenario,setScenario]=useState(""),[rto,setRto]=useState("240"),[rpo,setRpo]=useState("60");
 const load=useCallback(async()=>{setError("");try{const [p,c,b,d]=await Promise.all([api.drPosture(),api.drChecklist(),api.drBackups(50),api.drDrills(50)]);setPosture(p||{});setChecklist(c||{});setBackups(b?.backups||[]);setDrills(d?.drills||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load disaster recovery controls.")}},[]);
 useEffect(()=>{void load()},[load]);
 const addBackup=async(e:FormEvent)=>{e.preventDefault();setBusy("backup");try{await api.drRecordBackup({source,status:backupStatus,detail:detail||null});setDetail("");await load()}catch(x){setError(x instanceof Error?x.message:"Backup record failed")}finally{setBusy("")}};
 const start=async(e:FormEvent)=>{e.preventDefault();setBusy("drill");try{await api.drStartDrill({drill_type:type,scenario,rto_minutes_target:Number(rto),rpo_minutes_target:Number(rpo)});setScenario("");await load()}catch(x){setError(x instanceof Error?x.message:"Drill creation failed")}finally{setBusy("")}};
 const complete=async(id:string,status:string)=>{const notes=window.prompt("Outcome notes (optional):")||null;setBusy(id);try{await api.drCompleteDrill(id,{status,outcome_notes:notes});await load()}catch(x){setError(x instanceof Error?x.message:"Drill update failed")}finally{setBusy("")}};
 return <section className="page"><div className="page-header"><div><span className="eyebrow">PHASE 35</span><h1>Disaster recovery</h1><p>Backup verification, recovery drills, database connectivity and operational recovery readiness.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div>
 {error&&<div className="notice error">{error}</div>}
 <div className="stats-grid"><div className="stat-card"><span>Posture</span><strong>{posture.band||"—"}</strong><small>{posture.score??0}% readiness signal</small></div><div className="stat-card"><span>DB probe</span><strong>{posture.db_probe?.ok?"OK":"FAIL"}</strong><small>{posture.db_probe?.elapsed_ms??"—"} ms</small></div><div className="stat-card"><span>Backups</span><strong>{posture.backup_records??0}</strong><small>Verification records</small></div><div className="stat-card"><span>Passed drills</span><strong>{posture.last_passed_drill_id?"YES":"NONE"}</strong><small>Latest completed drill signal</small></div></div>
 <div className="card"><div className="card-header"><div><h2>Recovery checklist</h2><p>Operational guidance; RTO/RPO targets are policy guidance and should be tuned to the applicable SLA.</p></div></div><ul>{(checklist.steps||[]).map((x:any)=><li key={x.id}><strong>{x.id}</strong> — {x.step}</li>)}</ul></div>
 <div className="grid-2"><div className="card"><h2>Record backup verification</h2><form onSubmit={addBackup} className="form-grid"><label>Source<select value={source} onChange={e=>setSource(e.target.value)}><option>POSTGRES</option><option>OBJECT_STORE</option><option>WAL</option></select></label><label>Status<select value={backupStatus} onChange={e=>setBackupStatus(e.target.value)}><option>RECORDED</option><option>VERIFIED</option><option>FAILED</option></select></label><label className="full">Detail<textarea value={detail} onChange={e=>setDetail(e.target.value)} maxLength={2000}/></label><div className="full"><button disabled={busy==="backup"}>{busy==="backup"?"Saving…":"Record verification"}</button></div></form></div>
 <div className="card"><h2>Start recovery drill</h2><form onSubmit={start} className="form-grid"><label>Drill type<select value={type} onChange={e=>setType(e.target.value)}><option>TABLETOP</option><option>FAILOVER_SIM</option><option>RESTORE_TEST</option></select></label><label>RTO minutes<input type="number" min="1" value={rto} onChange={e=>setRto(e.target.value)}/></label><label>RPO minutes<input type="number" min="0" value={rpo} onChange={e=>setRpo(e.target.value)}/></label><label className="full">Scenario<textarea required minLength={5} value={scenario} onChange={e=>setScenario(e.target.value)} placeholder="Describe the recovery scenario"/></label><div className="full"><button disabled={busy==="drill"}>Start drill</button></div></form></div></div>
 <div className="grid-2"><div className="card"><h2>Recent backup records</h2><div className="table-wrap"><table><thead><tr><th>Source</th><th>Status</th><th>Recorded</th></tr></thead><tbody>{backups.map(b=><tr key={b.id}><td>{b.source}</td><td><span className="badge">{b.status}</span></td><td>{b.created_at?new Date(b.created_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div></div>
 <div className="card"><h2>Recovery drills</h2><div className="table-wrap"><table><thead><tr><th>Type</th><th>Status</th><th>Scenario</th><th>Action</th></tr></thead><tbody>{drills.map(d=><tr key={d.id}><td>{d.drill_type}</td><td><span className="badge">{d.status}</span></td><td>{d.scenario}</td><td>{["PLANNED","IN_PROGRESS"].includes(d.status)&&<select defaultValue="" onChange={e=>e.target.value&&void complete(d.id,e.target.value)}><option value="">Update</option><option>PASSED</option><option>FAILED</option><option>CANCELLED</option></select>}</td></tr>)}</tbody></table></div></div></div>
 <div className="notice"><strong>Important:</strong> the live database probe confirms connectivity only. It does not prove that a backup can be restored. Actual restore tests, backup retention and secret recovery must be verified operationally.</div></section>}
