import {useEffect,useState} from "react";
import {api} from "../api/client";
export function HealthExchangePage(){
 const [o,setO]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[type,setType]=useState("ENCOUNTER_SUMMARY"),[patient,setPatient]=useState(""),[source,setSource]=useState(""),[destination,setDestination]=useState(""),[payload,setPayload]=useState('{"event":"clinical_update"}'),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){try{const [a,b]=await Promise.all([api.healthExchangeOverview(),api.healthExchangeMessages({limit:100})]);setO(a);setRows(b)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[]);
 async function publish(){setError("");try{let p={};try{p=JSON.parse(payload)}catch{throw new Error("Payload must be valid JSON.")}await api.healthExchangePublish({message_id:"HX-"+Date.now()+"-"+Math.random().toString(36).slice(2,8),message_type:type,patient_id:patient||undefined,source_facility_id:source||undefined,destination_facility_id:destination||undefined,payload:p});setMessage("Exchange message accepted.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 return <section className="page-stack">
 <div className="page-header"><div><p className="eyebrow">Phase 50 · Interoperability backbone</p><h1>National health exchange</h1><p className="muted">A governed message-exchange layer for cross-facility and cross-system health information, financing and referral workflows.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div>
 {error&&<div className="error-banner">{error}</div>}{message&&<div className="notice-box">{message}</div>}
 {o&&<div className="stat-grid"><div className="stat-card"><span>Messages</span><strong>{o.messages}</strong><small>Exchange envelopes</small></div><div className="stat-card"><span>Accepted</span><strong>{o.accepted}</strong><small>Awaiting processing</small></div><div className="stat-card"><span>Processed</span><strong>{o.processed}</strong><small>Completed messages</small></div><div className="stat-card"><span>Failed</span><strong>{o.failed}</strong><small>Requires attention</small></div></div>}
 <section className="card"><h2>Publish exchange message</h2><p className="muted small">The exchange stores a governed envelope. Payloads are supplied by authorized systems; this layer does not silently invent or transform clinical content.</p><div className="form-grid"><label>Message type<select value={type} onChange={e=>setType(e.target.value)}><option>ENCOUNTER_SUMMARY</option><option>REFERRAL</option><option>TRANSFER</option><option>LAB_RESULT</option><option>IMAGING_RESULT</option><option>MEDICATION_EVENT</option><option>CLAIM_EVENT</option><option>ELIGIBILITY_EVENT</option><option>PREAUTHORIZATION_EVENT</option><option>DISCHARGE_SUMMARY</option></select></label><label>Patient UUID<input value={patient} onChange={e=>setPatient(e.target.value)} /></label><label>Source facility UUID<input value={source} onChange={e=>setSource(e.target.value)} /></label><label>Destination facility UUID<input value={destination} onChange={e=>setDestination(e.target.value)} /></label></div><label>Payload JSON<textarea rows={7} value={payload} onChange={e=>setPayload(e.target.value)}/></label><button onClick={()=>void publish()}>Publish message</button></section>
 <section className="card"><h2>Exchange ledger</h2><div className="table-wrap"><table><thead><tr><th>Message ID</th><th>Type</th><th>Patient</th><th>Source</th><th>Destination</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.message_id}</td><td>{x.message_type}</td><td>{x.patient_id||"—"}</td><td>{x.source_facility_id||"—"}</td><td>{x.destination_facility_id||"—"}</td><td>{x.status}</td><td>{x.created_at?new Date(x.created_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div></section>
 <div className="info-box"><strong>Exchange boundary:</strong> this phase establishes the transport and governance layer. It is designed to connect facilities, payers, referrals, laboratory, pharmacy and other systems without making any single payer the system boundary.</div>
 </section>
}
