import {useEffect,useState} from "react";
import {api} from "../api/client";
export function HealthExchangePage(){
 const [o,setO]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[inbound,setInbound]=useState<any[]>([]),[imported,setImported]=useState<any[]>([]),[type,setType]=useState("ENCOUNTER_SUMMARY"),[patient,setPatient]=useState(""),[source,setSource]=useState(""),[destination,setDestination]=useState(""),[payload,setPayload]=useState('{"event":"clinical_update"}'),[sourceNode,setSourceNode]=useState(""),[inboundPayload,setInboundPayload]=useState(""),[timelinePatient,setTimelinePatient]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){try{const [a,b,c]=await Promise.all([api.healthExchangeOverview(),api.healthExchangeMessages({limit:100}),api.hieInboundDocuments(100)]);setO(a);setRows(b);setInbound(c)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[]);
 async function receiveInbound(){setError("");setMessage("");try{if(!sourceNode.trim())throw new Error("Source HIE node ID is required.");const bundle=JSON.parse(inboundPayload);const result=await api.hieInboundReceive(bundle,sourceNode.trim(),bundle?.meta?.tag?.find?.((x:any)=>x?.system?.includes("/hie"))?.code);setMessage(result.idempotent_replay ? `Inbound Bundle replay detected; existing document ${result.validation_status} was reused without creating a duplicate.` : `Inbound document ${result.validation_status}; MPI status: ${result.mpi?.status || "UNRESOLVED"}.`);setInboundPayload("");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function resolveInbound(id:string){setError("");try{const result=await api.hieInboundResolve(id);setMessage(`MPI resolution: ${result.status}.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function importInbound(id:string){setError("");try{const result=await api.hieInboundImport(id);setMessage(`Clinical import complete: ${result.imported_count} imported, ${result.duplicate_count} duplicates, ${result.blocked_sensitive_count} sensitive items blocked.`);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function loadImported(){setError("");try{if(!timelinePatient.trim())throw new Error("Patient UUID is required.");setImported(await api.hieImportedPatientResources(timelinePatient.trim(),100))}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function publish(){setError("");try{let p={};try{p=JSON.parse(payload)}catch{throw new Error("Payload must be valid JSON.")}await api.healthExchangePublish({message_id:"HX-"+Date.now()+"-"+Math.random().toString(36).slice(2,8),message_type:type,patient_id:patient||undefined,source_facility_id:source||undefined,destination_facility_id:destination||undefined,payload:p});setMessage("Exchange message accepted.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 return <section className="page-stack">
 <div className="page-header"><div><p className="eyebrow">Phase 50 · Interoperability backbone</p><h1>National health exchange</h1><p className="muted">A governed message-exchange layer for cross-facility and cross-system health information, financing and referral workflows.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div>
 {error&&<div className="error-banner">{error}</div>}{message&&<div className="notice-box">{message}</div>}
 {o&&<div className="stat-grid"><div className="stat-card"><span>Messages</span><strong>{o.messages}</strong><small>Exchange envelopes</small></div><div className="stat-card"><span>Accepted</span><strong>{o.accepted}</strong><small>Awaiting processing</small></div><div className="stat-card"><span>Processed</span><strong>{o.processed}</strong><small>Completed messages</small></div><div className="stat-card"><span>Failed</span><strong>{o.failed}</strong><small>Requires attention</small></div></div>}
 <section className="card"><h2>Publish exchange message</h2><p className="muted small">The exchange stores a governed envelope. Payloads are supplied by authorized systems; this layer does not silently invent or transform clinical content.</p><div className="form-grid"><label>Message type<select value={type} onChange={e=>setType(e.target.value)}><option>ENCOUNTER_SUMMARY</option><option>REFERRAL</option><option>TRANSFER</option><option>LAB_RESULT</option><option>IMAGING_RESULT</option><option>MEDICATION_EVENT</option><option>CLAIM_EVENT</option><option>ELIGIBILITY_EVENT</option><option>PREAUTHORIZATION_EVENT</option><option>DISCHARGE_SUMMARY</option></select></label><label>Patient UUID<input value={patient} onChange={e=>setPatient(e.target.value)} /></label><label>Source facility UUID<input value={source} onChange={e=>setSource(e.target.value)} /></label><label>Destination facility UUID<input value={destination} onChange={e=>setDestination(e.target.value)} /></label></div><label>Payload JSON<textarea rows={7} value={payload} onChange={e=>setPayload(e.target.value)}/></label><button onClick={()=>void publish()}>Publish message</button></section>
 <section className="card"><h2>Receive inbound FHIR document</h2><p className="muted small">Only a trusted active HIE node may submit a document. The remote FHIR Patient.id is never used as a local patient identifier; MPI matching uses governed identifiers and demographics.</p><div className="form-grid"><label>Source HIE node UUID<input value={sourceNode} onChange={e=>setSourceNode(e.target.value)} /></label></div><label>FHIR Bundle JSON<textarea rows={10} value={inboundPayload} onChange={e=>setInboundPayload(e.target.value)} placeholder='Paste a FHIR Bundle received from the trusted node.'/></label><button onClick={()=>void receiveInbound()} disabled={!sourceNode||!inboundPayload}>Receive and resolve MPI</button></section>
 <section className="card"><h2>Inbound HIE worklist</h2><div className="table-wrap"><table><thead><tr><th>Document</th><th>Source</th><th>Type</th><th>Replay</th><th>Validation</th><th>MPI</th><th>Patient</th><th>Action</th></tr></thead><tbody>{inbound.map(x=><tr key={x.id}><td>{x.bundle_id||x.id}</td><td>{x.source_code||"—"}</td><td>{x.document_type}</td><td>{x.idempotent_replay?"REPLAY":"New"}</td><td>{x.validation_status}</td><td>{x.match_status}</td><td>{x.patient_id||"Not linked"}</td><td>{x.match_status!=="MATCHED"&&x.validation_status==="ACCEPTED"?<button onClick={()=>void resolveInbound(x.id)}>Retry MPI</button>:x.match_status==="MATCHED"?<button onClick={()=>void importInbound(x.id)}>Import clinical data</button>:"—"}</td></tr>)}</tbody></table></div></section>
 <section className="card"><h2>Imported patient timeline</h2><p className="muted small">Imported records are provenance-preserving HIE facts. They do not overwrite AfyaSync-native diagnoses, observations, medications, encounters or other local clinical records.</p><div className="form-grid"><label>Patient UUID<input value={timelinePatient} onChange={e=>setTimelinePatient(e.target.value)} /></label></div><button onClick={()=>void loadImported()} disabled={!timelinePatient.trim()}>Load imported timeline</button>{imported.length>0&&<div className="table-wrap"><table><thead><tr><th>When</th><th>Resource</th><th>Code</th><th>Summary</th><th>Sensitivity</th><th>Source</th></tr></thead><tbody>{imported.map(x=><tr key={x.id}><td>{x.effective_at?new Date(x.effective_at).toLocaleString():"Unknown"}</td><td>{x.resource_type}</td><td>{x.normalized_code||"—"}</td><td>{x.normalized_text||"—"}</td><td>{x.sensitivity}</td><td>{x.source_provenance?.source_code||x.source_provenance?.source_node_id||"—"}</td></tr>)}</tbody></table></div>}{timelinePatient&&imported.length===0&&<p className="muted small">No imported HIE clinical resources are available for this patient at this facility.</p>}</section>
 <section className="card"><h2>Exchange ledger</h2><div className="table-wrap"><table><thead><tr><th>Message ID</th><th>Type</th><th>Patient</th><th>Source</th><th>Destination</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.message_id}</td><td>{x.message_type}</td><td>{x.patient_id||"—"}</td><td>{x.source_facility_id||"—"}</td><td>{x.destination_facility_id||"—"}</td><td>{x.status}</td><td>{x.created_at?new Date(x.created_at).toLocaleString():"—"}</td></tr>)}</tbody></table></div></section>
 <div className="info-box"><strong>Exchange boundary:</strong> this phase establishes the transport and governance layer. It is designed to connect facilities, payers, referrals, laboratory, pharmacy and other systems without making any single payer the system boundary.</div>
 </section>
}
