import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import { api } from "../api/client";

type Contract={id:string;name:string;version:string;methods:string[];sandbox_path:string;production_paths:string[];auth:string;request:any;response:any};
export function PartnerSandboxPage(){
 const [contracts,setContracts]=useState<Contract[]>([]),[eligibility,setEligibility]=useState<any>(null),[preflight,setPreflight]=useState<any>(null),[hie,setHie]=useState<any>(null);
 const [org,setOrg]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[useCase,setUseCase]=useState(""),[member,setMember]=useState(""),[national,setNational]=useState(""),[note,setNote]=useState("");
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await api.partnerSandboxContracts();setContracts(r?.contracts||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load sandbox contracts.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const run=async(kind:string)=>{setBusy(kind);setError("");try{if(kind==="eligibility")setEligibility(await api.partnerSandboxEligibility({member_id:member||null,national_id:national||null}));if(kind==="preflight")setPreflight(await api.partnerSandboxClaimPreflight({sample:true}));if(kind==="hie")setHie(await api.partnerSandboxHieEcho({note:note||null}))}catch(e){setError(e instanceof Error?e.message:"Sandbox request failed.")}finally{setBusy("")}};
 const register=async(e:FormEvent)=>{e.preventDefault();setBusy("register");setError("");try{await api.partnerSandboxRegisterInterest({organisation:org,contact_email:email,contact_phone:phone||null,use_case:useCase});setOrg("");setEmail("");setPhone("");setUseCase("");alert("Partner interest registered.");}catch(x){setError(x instanceof Error?x.message:"Registration failed.")}finally{setBusy("")}};
 return <section className="page"><div className="page-header"><div><span className="eyebrow">PHASE 34</span><h1>Partner integration sandbox</h1><p>Test documented integration contracts without calling live SHA or production partner systems.</p></div><button className="secondary" onClick={()=>void load()} disabled={loading}>Refresh</button></div>
 {error&&<div className="notice error">{error}</div>}
 <div className="stats-grid"><div className="stat-card"><span>Contracts</span><strong>{contracts.length}</strong><small>Published sandbox contracts</small></div><div className="stat-card"><span>Mode</span><strong>SANDBOX</strong><small>No live SHA side effects</small></div><div className="stat-card"><span>Consent</span><strong>REQUIRED</strong><small>For HIE-style exchange</small></div></div>
 <div className="card"><div className="card-header"><div><h2>Integration contracts</h2><p>Versioned paths, request and response shapes for partner testing.</p></div></div><div className="table-wrap"><table><thead><tr><th>Contract</th><th>Version</th><th>Method</th><th>Sandbox path</th><th>Production path</th></tr></thead><tbody>{contracts.map(c=><tr key={c.id}><td><strong>{c.name}</strong><br/><code>{c.id}</code></td><td>{c.version}</td><td>{c.methods.join(", ")}</td><td><code>{c.sandbox_path}</code></td><td>{c.production_paths?.length?c.production_paths.map(x=><div key={x}><code>{x}</code></div>):"Not exposed"}</td></tr>)}</tbody></table></div></div>
 <div className="grid-2"><div className="card"><h2>Eligibility sandbox</h2><p>Deterministic test only; it is not a production SHA decision.</p><div className="form-grid"><label>Member ID<input value={member} onChange={e=>setMember(e.target.value)}/></label><label>National ID<input value={national} onChange={e=>setNational(e.target.value)}/></label><div className="full"><button onClick={()=>void run("eligibility")} disabled={busy==="eligibility"||(!member&&!national)}>Run sandbox check</button></div></div>{eligibility&&<pre className="code-block">{JSON.stringify(eligibility,null,2)}</pre>}</div>
 <div className="card"><h2>Claim preflight</h2><p>Uses a safe sample payload and does not submit a claim.</p><button onClick={()=>void run("preflight")} disabled={busy==="preflight"}>{busy==="preflight"?"Running…":"Run sample preflight"}</button>{preflight&&<pre className="code-block">{JSON.stringify(preflight,null,2)}</pre>}</div></div>
 <div className="grid-2"><div className="card"><h2>HIE echo</h2><p>Structured sandbox response; no live patient exchange.</p><input value={note} onChange={e=>setNote(e.target.value)} maxLength={200}/><button onClick={()=>void run("hie")} disabled={busy==="hie"}>Run HIE echo</button>{hie&&<pre className="code-block">{JSON.stringify(hie,null,2)}</pre>}</div>
 <div className="card"><h2>Partner interest</h2><p>Register an organisation for onboarding consideration.</p><form onSubmit={register} className="form-grid"><label>Organisation<input required value={org} onChange={e=>setOrg(e.target.value)}/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Use case<textarea required minLength={5} value={useCase} onChange={e=>setUseCase(e.target.value)}/></label><div className="full"><button disabled={busy==="register"}>Register interest</button></div></form></div></div>
 <div className="notice"><strong>Sandbox boundary:</strong> sample eligibility is deterministic, claim preflight is non-submitting, and HIE echo contains no live clinical exchange. Production credentials require onboarding and appropriate controls.</div></section>
}