import { useEffect,useState } from "react";
import { api } from "../api/client";
type Row={payer_id:string;payer_name:string;claims:number;billed:number;paid:number;payment_gap:number;collection_rate:number;denials:number;denial_rate:number;guardrail_exposure:number;recovery_outstanding:number;resolution_exposure:number;total_exposure:number;exposure_rate:number;recovery_yield:number;contract_status:string|null};
export default function PayerContractCashPage(){
 const [rows,setRows]=useState<Row[]>([]);const [totals,setTotals]=useState<any>({});const [days,setDays]=useState(90);const [busy,setBusy]=useState(true);
 useEffect(()=>{setBusy(true);api.get("/api/v1/contract-guardrails/payer-performance?days="+days).then((r:any)=>{setRows(r.payers||[]);setTotals(r.totals||{})}).finally(()=>setBusy(false))},[days]);
 const money=(n:number)=>"KES "+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
 return <div className="page"><div className="page-header"><div><h1>Payer Contract-to-Cash Performance</h1><p>Trace payer financial performance from claims through contract compliance, recovery and resolution.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>180 days</option><option value={365}>365 days</option></select></div>
 <div className="stat-grid"><div className="stat-card"><span>Total billed</span><strong>{money(totals.billed)}</strong></div><div className="stat-card"><span>Total paid</span><strong>{money(totals.paid)}</strong></div><div className="stat-card"><span>Payment gap</span><strong>{money(totals.payment_gap)}</strong></div><div className="stat-card"><span>Operational exposure</span><strong>{money(totals.exposure)}</strong></div></div>
 <section className="card"><h2>Payer performance</h2>{busy?<p>Loading…</p>:<div className="table-wrap"><table><thead><tr><th>Payer</th><th>Claims</th><th>Billed</th><th>Paid</th><th>Collection</th><th>Denial</th><th>Guardrails</th><th>Recovery</th><th>Resolution</th><th>Total exposure</th></tr></thead><tbody>{rows.map(x=><tr key={x.payer_id}><td><strong>{x.payer_name}</strong><br/><small>{x.contract_status||"No contract status"}</small></td><td>{x.claims}</td><td>{money(x.billed)}</td><td>{money(x.paid)}</td><td>{x.collection_rate}%</td><td>{x.denial_rate}%</td><td>{money(x.guardrail_exposure)}</td><td>{money(x.recovery_outstanding)}</td><td>{money(x.resolution_exposure)}</td><td><strong>{money(x.total_exposure)}</strong><br/><small>{x.exposure_rate}% of billed</small></td></tr>)}</tbody></table></div>}</section>
 <section className="card"><h2>How to use this view</h2><p>Exposure values are operational signals and may overlap when the same financial issue exists in multiple linked workflows. Use the underlying guardrail, recovery and resolution records before taking action.</p></section>
 </div>
}
