import {useEffect,useState} from "react";
const base=import.meta.env.VITE_API_URL||"";
const auth=()=>{const t=localStorage.getItem("access_token");return t?{Authorization:"Bearer "+t,"Content-Type":"application/json"}:{"Content-Type":"application/json"}};
async function req(path:string,options:any={}){const r=await fetch(base+path,{...options,headers:{...auth(),...(options.headers||{})}});if(!r.ok)throw new Error(await r.text()||"Request failed");return r.json();}
export default function PayerNegotiationPage(){
 const[data,setData]=useState<any>({total:0,draft:0,active:0,agreed:0,overdue:0}),[cases,setCases]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[items,setItems]=useState<any[]>([]),[contracts,setContracts]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [o,c]=await Promise.all([req("/api/v1/payer-negotiation/overview"),req("/api/v1/contract-renewal?days=365")]);setData(o);setCases(await req("/api/v1/payer-negotiation"));setContracts(c.contracts||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const select=async(c:any)=>{setSelected(c);try{setItems(await req("/api/v1/payer-negotiation/"+c.id+"/items"))}catch(e:any){setError(e.message)}};
 const create=async()=>{const contract=contracts.find(x=>x.status!=="CLOSED"&&x.status!=="SUSPENDED");if(!contract){setError("No eligible contract found");return}try{const x=await req("/api/v1/payer-negotiation",{method:"POST",body:JSON.stringify({contract_id:contract.contract_id,objective:"Prepare renewal and negotiate improved reimbursement, payment terms and operational terms."})});await load();await select(x)}catch(e:any){setError(e.message)}};
 const advance=async(status:string)=>{if(!selected)return;try{const x=await req("/api/v1/payer-negotiation/"+selected.id,{method:"PATCH",body:JSON.stringify({status})});setSelected(x);await load()}catch(e:any){setError(e.message)}};
 const add=async(type:string,title:string)=>{if(!selected)return;try{await req("/api/v1/payer-negotiation/"+selected.id+"/items",{method:"POST",body:JSON.stringify({item_type:type,title,priority:type==="TARIFF"?"HIGH":"MEDIUM",rationale:"Supported by current contract and performance evidence."})});await select(selected)}catch(e:any){setError(e.message)}};
 return <div className="page"><div className="page-header"><div><h1>Payer Negotiation Workspace</h1><p>Turn contract and payer performance evidence into a controlled negotiation workflow.</p></div><button onClick={create}>+ New negotiation</button></div>
 {error&&<div className="alert">{error}</div>}{loading?<div className="card">Loading…</div>:<>
 <div className="grid grid-3"><div className="card"><strong>{data.active}</strong><span>Active negotiations</span></div><div className="card"><strong>{data.agreed}</strong><span>Agreed / approved</span></div><div className="card"><strong>{data.overdue}</strong><span>Overdue</span></div></div>
 <section className="card"><h2>Negotiation cases</h2><div className="table-wrap"><table><thead><tr><th>Case</th><th>Contract</th><th>Status</th><th>Due</th><th>Open</th></tr></thead><tbody>{cases.map(c=><tr key={c.id} onClick={()=>select(c)}><td>{c.case_number}</td><td>{c.contract_id.slice(0,8)}…</td><td>{c.status}</td><td>{c.due_at?new Date(c.due_at).toLocaleDateString():"—"}</td><td><button>Open</button></td></tr>)}</tbody></table></div></section>
 {selected&&<section className="card"><h2>{selected.case_number}</h2><p>{selected.objective||"No objective set."}</p><div className="grid grid-3"><div><b>Status</b><div>{selected.status}</div></div><div><b>Evidence captured</b><div>{selected.evidence_snapshot?.captured_at?new Date(selected.evidence_snapshot.captured_at).toLocaleString():"Available"}</div></div><div><b>Target terms</b><div>{selected.target_position?.payment_terms_days??"—"} days</div></div></div>
 <div className="button-row"><button onClick={()=>advance("INTERNAL_REVIEW")}>Internal review</button><button onClick={()=>advance("READY_TO_SEND")}>Ready to send</button><button onClick={()=>advance("SENT")}>Sent</button><button onClick={()=>advance("IN_NEGOTIATION")}>In negotiation</button><button onClick={()=>advance("AGREED")}>Agree</button><button onClick={()=>advance("APPROVED")}>Approve</button><button onClick={()=>advance("CLOSED")}>Close</button></div>
 <h3>Negotiation items</h3><div className="button-row"><button onClick={()=>add("TARIFF","Tariff schedule revision")}>+ Tariff</button><button onClick={()=>add("PAYMENT_TERMS","Payment terms improvement")}>+ Payment terms</button><button onClick={()=>add("SLA","SLA / denial response terms")}>+ SLA</button><button onClick={()=>add("CLAIMS_WORKFLOW","Claims workflow enablement")}>+ Claims workflow</button><button onClick={()=>add("EMPANELMENT","Empanelment / network status")}>+ Empanelment</button></div>
 <div className="table-wrap"><table><thead><tr><th>Type</th><th>Item</th><th>Priority</th><th>Status</th><th>Request</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.item_type}</td><td>{i.title}</td><td>{i.priority}</td><td>{i.status}</td><td>{i.requested_value?JSON.stringify(i.requested_value):"—"}</td></tr>)}</tbody></table></div></section>}</>}</div>
}