import{useCallback,useEffect,useState}from"react";import{api}from"../api/client";
export function PilotHandoverPage(){const[evidence,setEvidence]=useState<any>({}),[handover,setHandover]=useState<any>({}),[county,setCounty]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
const load=useCallback(async()=>{setLoading(true);setError("");try{const x=await api.pilotHandoverEvidence(county);setEvidence(x||{});setHandover(county?(await api.pilotCountyHandover(county)):{});}catch(e){setError(e instanceof Error?e.message:"Unable to load pilot handover pack.")}finally{setLoading(false)}},[county]);useEffect(()=>{void load()},[]);
return <section className="page"><div className="page-header"><div><span className="eyebrow">PHASE 37</span><h1>Pilot handover</h1><p>Evidence pack and county operational handover workspace.</p></div><button className="secondary" onClick={()=>void load()} disabled={loading}>Refresh</button></div>{error&&<div className="notice error">{error}</div>}
<div className="card"><h2>County scope</h2><div className="form-grid"><label>County<input value={county} onChange={e=>setCounty(e.target.value)} placeholder="e.g. Kirinyaga"/></label><div><button onClick={()=>void load()} disabled={loading}>Load county pack</button></div></div></div>
<div className="stats-grid"><div className="stat-card"><span>Facilities</span><strong>{evidence.totals?.facilities_in_scope??0}</strong></div><div className="stat-card"><span>Active staff</span><strong>{evidence.totals?.active_staff??0}</strong></div><div className="stat-card"><span>Encounters</span><strong>{evidence.totals?.encounters??0}</strong></div><div className="stat-card"><span>Claims</span><strong>{evidence.totals?.claims??0}</strong></div></div>
<div className="grid-2"><div className="card"><h2>Evidence checklist</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{(evidence.evidence_checklist||[]).map((x:any)=><tr key={x.id}><td>{x.id}</td><td>{x.item}</td><td>{x.status}</td></tr>)}</tbody></table></div></div>
<div className="card"><h2>County handover</h2><ol>{(handover.handover_steps||[]).map((x:any)=><li key={x.id}>{x.step}</li>)}</ol>{handover.sign_off&&<div className="notice"><strong>Sign-off:</strong> {handover.sign_off.status} — {handover.sign_off.note}</div>}</div></div>
<div className="card"><h2>Facilities in scope</h2><div className="table-wrap"><table><thead><tr><th>Facility</th><th>Code</th><th>County</th><th>Status</th></tr></thead><tbody>{(evidence.facilities||[]).map((x:any)=><tr key={x.facility_id}><td>{x.name}</td><td>{x.mfl_or_code||"—"}</td><td>{x.county||"—"}</td><td>{x.status||"—"}</td></tr>)}</tbody></table></div></div>
<div className="card"><h2>Evidence endpoints</h2><ul>{(evidence.endpoint_index||[]).map((x:string)=><li key={x}><code>{x}</code></li>)}</ul><p>Operational sign-off remains a human governance process; this workspace provides the evidence and checklist.</p></div></section>}
