import {useEffect,useState} from "react";
import {api} from "../api/client";
export function ProviderNetworkPage(){
 const [o,setO]=useState<any>(null),[co,setCo]=useState<any>(null),[members,setMembers]=useState<any[]>([]),[services,setServices]=useState<any[]>([]),[contracts,setContracts]=useState<any[]>([]),[facility,setFacility]=useState(""),[network,setNetwork]=useState("NATIONAL"),[networkName,setNetworkName]=useState("National Provider Network"),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [service,setService]=useState({service_code:"",service_name:"",department_code:"",tariff_amount:""}),[contract,setContract]=useState({contract_reference:"",payment_terms_days:"30",notes:""});
 async function load(){setError("");try{const [a,b,c,d,e]=await Promise.all([api.providerNetworkOverview(),api.providerNetworkMemberships(),api.providerNetworkServices(),api.providerNetworkContracts(),api.providerContractingOverview()]);setO(a);setMembers(b);setServices(c);setContracts(d);setCo(e)}catch(e){setError(e instanceof Error?e.message:"PROVIDER_NETWORK_REQUEST_FAILED")}}
 useEffect(()=>{void load()},[]);
 async function createMembership(){try{await api.providerNetworkCreateMembership({facility_id:facility,network_code:network,network_name:networkName});setMessage("Provider membership created.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function createService(){try{await api.providerNetworkCreateService({facility_id:facility,network_code:network,...service,tariff_amount:service.tariff_amount?Number(service.tariff_amount):undefined});setMessage("Network service added.");setService({service_code:"",service_name:"",department_code:"",tariff_amount:""});await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function createContract(){try{await api.providerNetworkCreateContract({facility_id:facility,network_code:network,...contract,payment_terms_days:Number(contract.payment_terms_days)});setMessage("Provider contract created.");await load()}catch(e){setError(e instanceof Error?e.message:String(e))}}
 return <section className="page-stack">
 <div className="page-header"><div><p className="eyebrow">Phase 49 · Provider-side national infrastructure</p><h1>National provider network</h1><p className="muted">A governed provider layer connecting facilities, services, credentials, referrals and financing participation across multiple networks.</p></div><button className="secondary" onClick={()=>void load()}>Refresh</button></div>
 {error&&<div className="error-banner">{error}</div>}{message&&<div className="notice-box">{message}</div>}
 {co&&<div className="stat-grid"><div className="stat-card"><span>Pending verification</span><strong>{co.pending_verification}</strong><small>Provider files needing verification</small></div><div className="stat-card"><span>Negotiating</span><strong>{co.negotiating_contracts}</strong><small>Contracts awaiting acceptance</small></div><div className="stat-card"><span>Renewals due</span><strong>{co.renewals_due}</strong><small>Contracts requiring renewal action</small></div></div>}{o&&<div className="stat-grid"><div className="stat-card"><span>Network memberships</span><strong>{o.memberships}</strong><small>{o.active_memberships} active</small></div><div className="stat-card"><span>Network services</span><strong>{o.services}</strong><small>Published service records</small></div><div className="stat-card"><span>Contracts</span><strong>{o.contracts}</strong><small>{o.active_contracts} active</small></div><div className="stat-card"><span>Networks</span><strong>{o.networks.length}</strong><small>Financing/referral networks</small></div></div>}
 <section className="card"><h2>Register provider participation</h2><div className="form-grid"><label>Facility UUID<input value={facility} onChange={e=>setFacility(e.target.value)} placeholder="Facility UUID"/></label><label>Network code<input value={network} onChange={e=>setNetwork(e.target.value)}/></label><label>Network name<input value={networkName} onChange={e=>setNetworkName(e.target.value)}/></label></div><button onClick={()=>void createMembership()}>Register membership</button></section>
 <section className="grid-2"><div className="card"><h2>Publish a service</h2><label>Service code<input value={service.service_code} onChange={e=>setService({...service,service_code:e.target.value})}/></label><label>Service name<input value={service.service_name} onChange={e=>setService({...service,service_name:e.target.value})}/></label><label>Department code<input value={service.department_code} onChange={e=>setService({...service,department_code:e.target.value})}/></label><label>Tariff (KES)<input value={service.tariff_amount} onChange={e=>setService({...service,tariff_amount:e.target.value})}/></label><button onClick={()=>void createService()}>Publish service</button></div>
 <div className="card"><h2>Provider contract</h2><label>Contract reference<input value={contract.contract_reference} onChange={e=>setContract({...contract,contract_reference:e.target.value})}/></label><label>Payment terms (days)<input type="number" value={contract.payment_terms_days} onChange={e=>setContract({...contract,payment_terms_days:e.target.value})}/></label><label>Notes<textarea value={contract.notes} onChange={e=>setContract({...contract,notes:e.target.value})}/></label><button onClick={()=>void createContract()}>Create contract</button></div></section>
 <section className="card"><div className="card-header"><div><h2>Provider memberships</h2><p className="muted">Participation is explicitly governed; a facility is not automatically in every network.</p></div></div><div className="table-wrap"><table><thead><tr><th>Facility</th><th>Network</th><th>Status</th><th>Verification</th><th>Actions</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td>{m.facility_id}</td><td>{m.network_name}</td><td>{m.participation_status}</td><td>{m.credential_status}</td><td>{m.license_verified_at?"✓":"—"} {m.credential_verified_at?"✓":"—"} {m.service_verified_at?"✓":"—"}</td><td><div className="button-row"><button onClick={()=>void api.providerVerifyMembership(m.id,"LICENSE").then(load)}>Verify licence</button><button onClick={()=>void api.providerVerifyMembership(m.id,"CREDENTIAL").then(load)}>Verify credentials</button><button onClick={()=>void api.providerVerifyMembership(m.id,"SERVICE").then(load)}>Verify services</button></div></td></tr>)}</tbody></table></div></section>
 <section className="card"><h2>Published services</h2><div className="table-wrap"><table><thead><tr><th>Service</th><th>Code</th><th>Facility</th><th>Network</th><th>Tariff</th></tr></thead><tbody>{services.map(s=><tr key={s.id}><td>{s.service_name}</td><td>{s.service_code}</td><td>{s.facility_id}</td><td>{s.network_code}</td><td>{s.tariff_amount==null?"—":"KES "+Number(s.tariff_amount).toLocaleString()}</td></tr>)}</tbody></table></div></section>
 <section className="card"><h2>Provider contracts</h2><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Facility</th><th>Network</th><th>Status</th><th>Payment terms</th><th>Lifecycle</th></tr></thead><tbody>{contracts.map(c=><tr key={c.id}><td>{c.contract_reference}</td><td>{c.facility_id}</td><td>{c.network_code}</td><td>{c.status}</td><td>{c.payment_terms_days} days</td><td><div className="button-row">{c.status==="DRAFT"&&<button onClick={()=>void api.providerNegotiateContract(c.id).then(load)}>Start negotiation</button>}{c.status==="NEGOTIATING"&&<button onClick={()=>void api.providerAcceptContract(c.id).then(load)}>Accept contract</button>}{c.status==="ACTIVE"&&<button onClick={()=>void api.providerContractEvents(c.id).then(events=>setMessage(`${events.length} lifecycle events recorded.`))}>View history</button>}</div></td></tr>)}</tbody></table></div></section>
 </section>
}
