import {useState} from "react";
import {api} from "../api/client";
export function ReferralRoutingPage(){
 const [service,setService]=useState(""),[county,setCounty]=useState(""),[network,setNetwork]=useState(""),[day,setDay]=useState(new Date().toISOString().slice(0,10)),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function search(){setLoading(true);setError("");try{const r=await api.referralRoutingOptions({service_code:service,county:county||undefined,network_code:network||undefined,day,limit:30});setRows(r.options||[])}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 return <section className="page-stack"><header className="page-heading"><div><p className="eyebrow">Phase 53 · Routing intelligence</p><h1>Intelligent referral routing</h1><p className="muted">Find active network providers with current service capacity before a referral is directed.</p></div></header>
 {error&&<div className="error-banner">{error}</div>}
 <article className="card"><h2>Routing request</h2><div className="filter-row"><label>Service code<input value={service} onChange={e=>setService(e.target.value)} placeholder="e.g. CARDIOLOGY" /></label><label>County<input value={county} onChange={e=>setCounty(e.target.value)} placeholder="Optional" /></label><label>Network<input value={network} onChange={e=>setNetwork(e.target.value)} placeholder="Optional" /></label><label>Date<input type="date" value={day} onChange={e=>setDay(e.target.value)} /></label><button className="button filter-action" disabled={!service||loading} onClick={()=>void search()}>{loading?"Routing…":"Find providers"}</button></div></article>
 <article className="card"><div className="card-header"><div><h2>Available routing options</h2><p className="muted">Options are generated from active network participation and current capacity. This does not automatically create a referral.</p></div></div><div className="table-wrap"><table><thead><tr><th>Facility</th><th>Service</th><th>Network</th><th>Capacity</th><th>Booked</th><th>Remaining</th><th>Referral</th><th>Routing basis</th></tr></thead><tbody>{rows.map(r=><tr key={r.facility_id+r.network_code+r.service_code}><td><strong>{r.facility_name}</strong><div className="muted small">{r.county||"—"}</div></td><td>{r.service_name}<div className="muted small">{r.service_code}</div></td><td>{r.network_code}</td><td>{r.daily_capacity}</td><td>{r.booked}</td><td>{r.remaining}</td><td>{r.referral_required?"Required":"Not flagged"}</td><td>{r.route_reason?.join(" · ")}</td></tr>)}</tbody></table>{!rows.length&&!loading&&<p className="muted">No currently available routing options for this request.</p>}</div></article>
 <div className="info-box"><strong>Routing boundary:</strong> the engine exposes transparent routing factors rather than silently making a clinical decision. Clinical judgment, patient consent and facility acceptance remain part of the referral workflow.</div></section>
}