import { useState } from "react";
import { createReferralBooking } from "../api/referralBookingApi";
export function ReferralBookingPage() {
  const [patientId,setPatientId]=useState(""); const [encounterId,setEncounterId]=useState(""); const [facilityId,setFacilityId]=useState(""); const [departmentId,setDepartmentId]=useState(""); const [serviceCode,setServiceCode]=useState(""); const [networkCode,setNetworkCode]=useState(""); const [appointmentAt,setAppointmentAt]=useState(""); const [reason,setReason]=useState(""); const [notes,setNotes]=useState(""); const [result,setResult]=useState<any>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(){ setLoading(true); setError(""); setResult(null); try { const key=`referral-booking-${patientId}-${facilityId}-${appointmentAt}`; setResult(await createReferralBooking({patient_id:patientId,encounter_id:encounterId,destination_facility_id:facilityId,destination_department_id:departmentId,service_code:serviceCode,network_code:networkCode,appointment_at:new Date(appointmentAt).toISOString(),reason,notes:notes||undefined},key)); } catch(e){setError(e instanceof Error?e.message:String(e));} finally{setLoading(false);} }
  return <section className="page-stack"><header className="page-heading"><div><p className="eyebrow">Phase 54 · Decision & booking exchange</p><h1>Referral decision & booking</h1><p className="muted">Convert a selected routing option into one protected referral, appointment and care-coordination chain.</p></div></header>
  {error&&<div className="error-banner">{error}</div>}
  <article className="card"><h2>Book a routed referral</h2><div className="filter-row"><label>Patient ID<input value={patientId} onChange={e=>setPatientId(e.target.value)} /></label><label>Encounter ID<input value={encounterId} onChange={e=>setEncounterId(e.target.value)} /></label><label>Destination facility ID<input value={facilityId} onChange={e=>setFacilityId(e.target.value)} /></label><label>Department ID<input value={departmentId} onChange={e=>setDepartmentId(e.target.value)} /></label><label>Service code<input value={serviceCode} onChange={e=>setServiceCode(e.target.value)} /></label><label>Network code<input value={networkCode} onChange={e=>setNetworkCode(e.target.value)} /></label><label>Appointment time<input type="datetime-local" value={appointmentAt} onChange={e=>setAppointmentAt(e.target.value)} /></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} /></label><label>Notes<input value={notes} onChange={e=>setNotes(e.target.value)} /></label><button className="button filter-action" disabled={loading||!patientId||!encounterId||!facilityId||!departmentId||!serviceCode||!networkCode||!appointmentAt||!reason} onClick={()=>void submit()}>{loading?"Booking…":"Confirm referral & appointment"}</button></div></article>
  {result&&<article className="card"><h2>Booking confirmed</h2><div className="table-wrap"><table><tbody><tr><th>Reference</th><td>{result.booking_reference}</td></tr><tr><th>Referral</th><td>{result.referral_id}</td></tr><tr><th>Appointment</th><td>{result.appointment_id}</td></tr><tr><th>Care coordination</th><td>{result.coordination_case_id}</td></tr><tr><th>Status</th><td>{result.status}</td></tr><tr><th>Appointment time</th><td>{result.appointment_at}</td></tr></tbody></table></div></article>}
  <div className="info-box"><strong>Safety boundary:</strong> booking is idempotent and capacity-checked. It does not override clinical judgment, consent, emergency escalation, or the receiving facility's operational obligations.</div></section>;
}
