import { useEffect,useState } from "react";
import { api } from "../api/client";
const money=(v:any)=>`KES ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
export default function RevenueResolutionPage(){
 const [overview,setOverview]=useState<any>(null),[cases,setCases]=useState<any[]>([]),[sla,setSla]=useState<any>(null),[queue,setQueue]=useState<any[]>([]),[message,setMessage]=useState("");
 async function load(){const responses=await Promise.all([api.revenueResolutionOverview(),api.revenueResolutionCases(),api.payerSlaOverview(),api.payerSlaEscalationQueue()]);setOverview(responses[0]);setCases(responses[1]);setSla(responses[2]);setQueue(responses[3]?.items||[]);}
 async function sync(){try{const r=await api.revenueResolutionSync();const s=await api.payerSlaSync();setMessage(`Synchronized ${r.created} revenue cases; ${s.initialized} SLA clocks initialized, ${s.response_breaches} response breaches, ${s.breached} resolution breaches, ${s.escalated} escalations and ${s.appeal_risk} appeals at risk.`);await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function update(id:string,status:string){try{await api.revenueResolutionUpdate(id,{status});await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:String(e)));},[]);
 return <div className="page-stack">
  <div className="page-header"><div><p className="eyebrow">Phase 64 · Revenue operations</p><h1>Revenue Resolution Centre</h1><p className="muted">One operational queue for denials, recovery, anomaly investigation and collections.</p></div><button className="secondary" onClick={()=>void sync()}>Sync revenue signals</button></div>
  {message&&<div className="notice-box">{message}</div>}
  {overview&&<div className="stat-grid">{Object.entries(overview.active_priorities||{}).map((entry:any)=><div className="stat-card" key={entry[0]}><span>{entry[0]}</span><strong>{entry[1]}</strong><small>active cases</small></div>)}</div>}
  <section className="card"><h2>Payer SLA & denial intelligence</h2>{sla&&<div className="stat-grid">{Object.entries(sla.sla?.by_status||{}).map((entry:any)=><div className="stat-card" key={entry[0]}><span>{String(entry[0]).replace("_"," ")}</span><strong>{entry[1].count}</strong><small>{money(entry[1].amount_at_risk)} at risk</small></div>)}</div>}<div className="table-wrap"><table><thead><tr><th>Payer</th><th>Claims</th><th>Denials</th><th>Denial rate</th><th>Collection rate</th></tr></thead><tbody>{(sla?.performance?.payers||[]).map((p:any)=><tr key={p.payer_id||p.payer_name}><td>{p.payer_name}</td><td>{p.claims}</td><td>{p.denials}</td><td>{p.denial_rate}%</td><td>{p.collection_rate}%</td></tr>)}</tbody></table></div></section>
  <section className="card"><h2>SLA action queue</h2><div className="table-wrap"><table><thead><tr><th>Case</th><th>Status</th><th>Priority</th><th>Response</th><th>Resolution</th><th>Appeal</th><th>Action</th></tr></thead><tbody>{queue.map((x:any)=><tr key={x.case_id}><td>{x.case_number}</td><td>{x.sla_status}</td><td>{x.priority}</td><td>{x.hours_to_response==null?"Responded":`${x.hours_to_response}h`}</td><td>{x.hours_to_sla}h</td><td>{x.hours_to_appeal==null?"—":`${x.hours_to_appeal}h`}</td><td>{x.recommended_action}</td></tr>)}</tbody></table></div></section>
  <section className="card"><h2>Active resolution cases</h2><div className="table-wrap"><table><thead><tr><th>Priority</th><th>Source</th><th>Issue</th><th>At risk</th><th>Status</th><th>Due</th><th>Action</th></tr></thead><tbody>{cases.map(x=><tr key={x.id}><td>{x.priority}</td><td>{x.source_type}</td><td>{x.title}</td><td>{money(x.amount_at_risk)}</td><td>{x.status}</td><td>{x.due_at?new Date(x.due_at).toLocaleDateString():"—"}</td><td>{x.status!=="CLOSED"&&<><button className="secondary" onClick={()=>void update(x.id,"IN_REVIEW")}>Review</button>{" "}<button className="secondary" onClick={()=>void update(x.id,"RESOLVED")}>Resolve</button></>}</td></tr>)}</tbody></table></div></section>
 </div>;
}