import { useEffect,useState } from "react";
import { api } from "../api/client";
const money=(v:any)=>`KES ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
export default function RevenueResolutionPage(){
 const [overview,setOverview]=useState<any>(null),[cases,setCases]=useState<any[]>([]),[sla,setSla]=useState<any>(null),[queue,setQueue]=useState<any>(null),[message,setMessage]=useState("");
 async function load(){const [o,c,s]=await Promise.all([api.revenueResolutionOverview(),api.revenueResolutionCases(),api.payerSlaOverview(),api.payerSlaEscalationQueue()]);setOverview(o);setCases(c);setSla(s);setQueue(q);}
 async function sync(){try{const r=await api.revenueResolutionSync();const s=await api.payerSlaSync();setMessage(`Synchronized ${r.created} revenue cases and initialized ${s.initialized} SLA clocks; ${s.breached} breached, ${s.escalated} escalated.`);await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function update(id:string,status:string){try{await api.revenueResolutionUpdate(id,{status});await load();}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 useEffect(()=>{void load().catch(e=>setMessage(e instanceof Error?e.message:String(e)));},[]);
 return <div className="page-stack">
  <div className="page-header"><div><p className="eyebrow">Phase 64 · Revenue operations</p><h1>Revenue Resolution Centre</h1><p className="muted">One operational queue for denials, recovery, anomaly investigation and collections.</p></div><button className="secondary" onClick={()=>void sync()}>Sync revenue signals</button></div>
  {message&&<div className="notice-box">{message}</div>}
  {overview&&<div className="stat-grid">{Object.entries(overview.active_priorities||{}).map(([p,v]:[string,any])=><div className="stat-card" key={p}><span>{p}</span><strong>{v}</strong><small>active cases</small></div>)}</div>}
  <section className="card"><h2>Payer SLA & denial intelligence</h2>{sla&&<div className="stat-grid">{Object.entries(sla.sla?.by_status||{}).map(([s,v]:[string,any])=><div className="stat-card" key={s}><span>{s.replace("_"," ")}</span><strong>{v.count}</strong><small>{money(v.amount_at_risk)} at risk</small></div>)}</div>}<div className="table-wrap"><table><thead><tr><th>Payer</th><th>Claims</th><th>Denials</th><th>Denial rate</th><th>Collection rate</th></tr></thead><tbody>{(sla?.performance?.payers||[]).map((p:any)=><tr key={p.payer_id||p.payer_name}><td>{p.payer_name}</td><td>{p.claims}</td><td>{p.denials}</td><td>{p.denial_rate}%</td><td>{p.collection_rate}%</td></tr>)}</tbody></table></div></section><section className="card"><h2>SLA action queue</h2><div className="table-wrap"><table><thead><tr><th>Case</th><th>Status</th><th>Priority</th><th>Hours to SLA</th><th>At risk</th><th>Recommended action</th></tr></thead><tbody>{(queue?.items||[]).map((x:any)=><tr key={x.case_id}><td>{x.case_number}</td><td>{x.sla_status}</td><td>{x.priority}</td><td>{x.hours_to_sla}</td><td>{money(x.amount_at_risk)}</td><td>{x.recommended_action}</td></tr>)}</tbody></table></div></section><section className="card"><h2>Active resolution cases</h2><div className="table-wrap"><table><thead><tr><th>Priority</th><th>Source</th><th>Issue</th><th>At risk</th><th>Status</th><th>Due</th><th>Action</th></tr></thead><tbody>{cases.map(x=><tr key={x.id}><td>{x.priority}</td><td>{x.source_type}</td><td>{x.title}</td><td>{money(x.amount_at_risk)}</td><td>{x.status}</td><td>{x.due_at?new Date(x.due_at).toLocaleDateString():"—"}</td><td>{x.status!=="CLOSED"&&<><button className="secondary" onClick={()=>void update(x.id,"IN_REVIEW")}>Review</button>{" "}<button className="secondary" onClick={()=>void update(x.id,"RESOLVED")}>Resolve</button></>}</td></tr>)}</tbody></table></div></section>
 </div>;
}