"""Auto-generated router registry for Phase 140 main bootstrap. Developed by BAHATI GAD WANGWE."""
ROUTERS: list[tuple[str, str, str]] = [
    ("app.government.router", "router", "government_router"),
    ("app.context.router", "router", "context_router"),
    ("app.business_continuity.router", "router", "business_continuity_router"),
    ("app.national_audit.router", "router", "national_audit_router"),
    ("app.end_to_end_simulation.router", "router", "end_to_end_simulation_router"),
    ("app.production_hardening.router", "router", "production_hardening_router"),
    ("app.product_readiness.router", "router", "product_readiness_router"),
    ("app.tenancy.router", "router", "tenancy_router"),
    ("app.auth.patient_router", "router", "patient_auth_router"),
    ("app.patients.router", "router", "patients_router"),
    ("app.patient_timeline.router", "router", "patient_timeline_router"),
    ("app.national_identity.router", "router", "national_identity_router"),
    ("app.coverage.router", "router", "coverage_router"),
    ("app.can_i_get_this.router", "router", "can_i_get_this_router"),
    ("app.sha_eligibility.router", "router", "sha_eligibility_router"),
    ("app.payer_network.router", "router", "payer_network_router"),
    ("app.benefits.router", "router", "benefits_router"),
    ("app.admissions.router", "router", "admissions_router"),
    ("app.preauthorizations.router", "router", "preauthorizations_router"),
    ("app.emergency.router", "router", "emergency_router"),
    ("app.encounters.router", "router", "encounters_router"),
    ("app.clinical.router", "router", "clinical_router"),
    ("app.clinical.worklist_routes", "worklist_router", "worklist_router"),
    ("app.appointments.router", "router", "appointments_router"),
    ("app.billing.router", "router", "billing_router"),
    ("app.claims.router", "router", "claims_router"),
    ("app.claims.preflight_router", "router", "claim_preflight_router"),
    ("app.laboratory.router", "router", "laboratory_router"),
    ("app.pharmacy.router", "router", "pharmacy_router"),
    ("app.radiology.router", "router", "radiology_router"),
    ("app.auth", "router", "auth_router"),
]
