"""maternity ANC delivery and newborn records
Revision ID: 0040_maternity
Revises: 0039_theatre
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0040_maternity";down_revision="0039_theatre";branch_labels=None;depends_on=None

def upgrade():
 op.create_table("pregnancies",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("patient_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("persons.id",ondelete="RESTRICT"),nullable=False),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="RESTRICT"),nullable=False),sa.Column("gravida",sa.Integer),sa.Column("para",sa.Integer),sa.Column("lmp",sa.Date),sa.Column("estimated_due_date",sa.Date),sa.Column("gestational_age_weeks",sa.Integer),sa.Column("risk_level",sa.String(30),nullable=False,server_default="ROUTINE"),sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("antenatal_visits",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("pregnancy_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("pregnancies.id",ondelete="RESTRICT"),nullable=False),sa.Column("patient_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("persons.id",ondelete="RESTRICT"),nullable=False),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="RESTRICT"),nullable=False),sa.Column("clinician_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("staff.id",ondelete="RESTRICT"),nullable=False),sa.Column("visit_date",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("gestational_age_weeks",sa.Integer),sa.Column("blood_pressure",sa.String(30)),sa.Column("weight",sa.String(30)),sa.Column("fetal_heart_rate",sa.String(30)),sa.Column("findings",sa.Text),sa.Column("plan",sa.Text))
 op.create_table("deliveries",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("pregnancy_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("pregnancies.id",ondelete="RESTRICT"),nullable=False),sa.Column("mother_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("persons.id",ondelete="RESTRICT"),nullable=False),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="RESTRICT"),nullable=False),sa.Column("delivery_datetime",sa.DateTime(timezone=True),nullable=False),sa.Column("mode",sa.String(40),nullable=False),sa.Column("outcome",sa.String(40),nullable=False),sa.Column("newborn_count",sa.Integer,nullable=False,server_default="1"),sa.Column("complications",sa.Text),sa.Column("notes",sa.Text),sa.Column("recorded_by",postgresql.UUID(as_uuid=True),sa.ForeignKey("staff.id",ondelete="RESTRICT"),nullable=False))
 op.create_table("newborns",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("delivery_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("deliveries.id",ondelete="RESTRICT"),nullable=False),sa.Column("mother_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("persons.id",ondelete="RESTRICT"),nullable=False),sa.Column("patient_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("persons.id",ondelete="RESTRICT")),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="RESTRICT"),nullable=False),sa.Column("sex",sa.String(20)),sa.Column("birth_weight",sa.String(30)),sa.Column("apgar_1",sa.Integer),sa.Column("apgar_5",sa.Integer),sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"),sa.Column("notes",sa.Text))
 for t,c in [("pregnancies","patient_id"),("antenatal_visits","patient_id"),("deliveries","mother_id"),("newborns","mother_id")]:op.create_index(f"ix_{t}_{c}",t,[c])

def downgrade():
 op.drop_table("newborns");op.drop_table("deliveries");op.drop_table("antenatal_visits");op.drop_table("pregnancies")
