"""blood bank and transfusion workflow
Revision ID: 0042_blood_bank
Revises: 0041_child_health
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0042_blood_bank";down_revision="0041_child_health";branch_labels=None;depends_on=None

def upgrade():
 op.create_table("blood_units",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="RESTRICT"),nullable=False),sa.Column("donation_number",sa.String(80),unique=True,nullable=False),sa.Column("blood_group",sa.String(5),nullable=False),sa.Column("component",sa.String(40),nullable=False,server_default="WHOLE_BLOOD"),sa.Column("collected_at",sa.DateTime(timezone=True)),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(30),nullable=False,server_default="AVAILABLE"),sa.Column("screening_status",sa.String(30),nullable=False,server_default="PENDING"),sa.Column("storage_location",sa.String(100)),sa.Column("notes",sa.Text))
 op.create_table("blood_requests",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("patient_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("persons.id",ondelete="RESTRICT"),nullable=False),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="RESTRICT"),nullable=False),sa.Column("encounter_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("encounters.id",ondelete="RESTRICT")),sa.Column("blood_group",sa.String(5)),sa.Column("component",sa.String(40),nullable=False,server_default="WHOLE_BLOOD"),sa.Column("units_requested",sa.Integer,nullable=False,server_default="1"),sa.Column("urgency",sa.String(30),nullable=False,server_default="ROUTINE"),sa.Column("indication",sa.Text),sa.Column("status",sa.String(30),nullable=False,server_default="REQUESTED"),sa.Column("requested_by",postgresql.UUID(as_uuid=True),sa.ForeignKey("staff.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
 op.create_table("blood_crossmatches",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("request_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blood_requests.id",ondelete="RESTRICT"),nullable=False),sa.Column("blood_unit_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blood_units.id",ondelete="RESTRICT"),nullable=False),sa.Column("patient_blood_group",sa.String(5),nullable=False),sa.Column("result",sa.String(30),nullable=False),sa.Column("performed_by",postgresql.UUID(as_uuid=True),sa.ForeignKey("staff.id",ondelete="RESTRICT"),nullable=False),sa.Column("performed_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("notes",sa.Text))
 op.create_table("transfusions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("request_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blood_requests.id",ondelete="RESTRICT"),nullable=False),sa.Column("blood_unit_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("blood_units.id",ondelete="RESTRICT"),nullable=False),sa.Column("patient_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("persons.id",ondelete="RESTRICT"),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(30),nullable=False,server_default="STARTED"),sa.Column("observations",sa.Text),sa.Column("administered_by",postgresql.UUID(as_uuid=True),sa.ForeignKey("staff.id",ondelete="RESTRICT"),nullable=False))
 op.create_table("transfusion_reactions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("transfusion_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("transfusions.id",ondelete="RESTRICT"),nullable=False),sa.Column("reaction_type",sa.String(80),nullable=False),sa.Column("severity",sa.String(30),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("action_taken",sa.Text),sa.Column("outcome",sa.Text),sa.Column("reported_by",postgresql.UUID(as_uuid=True),sa.ForeignKey("staff.id",ondelete="RESTRICT"),nullable=False))
 for t,c in [("blood_units","facility_id"),("blood_requests","facility_id"),("blood_crossmatches","request_id"),("transfusions","patient_id"),("transfusion_reactions","transfusion_id")]: op.create_index(f"ix_{t}_{c}",t,[c])

def downgrade():
 op.drop_table("transfusion_reactions");op.drop_table("transfusions");op.drop_table("blood_crossmatches");op.drop_table("blood_requests");op.drop_table("blood_units")
