"""provider network participation, services and contracts
Revision ID: 0104_provider_network
Revises: 0103_financing_wallet
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0104_provider_network";down_revision="0103_financing_wallet";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("provider_network_memberships",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="CASCADE"),nullable=False),sa.Column("network_code",sa.String(80),nullable=False),sa.Column("network_name",sa.String(200),nullable=False),sa.Column("participation_status",sa.String(30),nullable=False,server_default="PENDING"),sa.Column("effective_from",sa.DateTime(timezone=True)),sa.Column("effective_to",sa.DateTime(timezone=True)),sa.Column("credential_status",sa.String(30),nullable=False,server_default="PENDING"),sa.Column("referral_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("claims_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("facility_id","network_code",name="uq_provider_network_membership"))
 op.create_index("ix_provider_network_memberships_facility_id","provider_network_memberships",["facility_id"]);op.create_index("ix_provider_network_memberships_network_code","provider_network_memberships",["network_code"]);op.create_index("ix_provider_network_memberships_participation_status","provider_network_memberships",["participation_status"])
 op.create_table("provider_network_services",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="CASCADE"),nullable=False),sa.Column("network_code",sa.String(80),nullable=False),sa.Column("service_code",sa.String(80),nullable=False),sa.Column("service_name",sa.String(200),nullable=False),sa.Column("department_code",sa.String(50)),sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"),sa.Column("tariff_amount",sa.Numeric(14,2)),sa.Column("currency",sa.String(3),nullable=False,server_default="KES"),sa.Column("referral_required",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("facility_id","service_code","network_code",name="uq_provider_network_service"))
 op.create_index("ix_provider_network_services_facility_id","provider_network_services",["facility_id"]);op.create_index("ix_provider_network_services_status","provider_network_services",["status"]);op.create_index("ix_provider_network_service_network","provider_network_services",["network_code","service_code"])
 op.create_table("provider_network_contracts",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("facility_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("facilities.id",ondelete="CASCADE"),nullable=False),sa.Column("network_code",sa.String(80),nullable=False),sa.Column("contract_reference",sa.String(120),nullable=False,unique=True),sa.Column("status",sa.String(30),nullable=False,server_default="DRAFT"),sa.Column("payment_terms_days",sa.Integer(),nullable=False,server_default="30"),sa.Column("notes",sa.Text()),sa.Column("effective_from",sa.DateTime(timezone=True)),sa.Column("effective_to",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
 op.create_index("ix_provider_network_contracts_facility_id","provider_network_contracts",["facility_id"]);op.create_index("ix_provider_network_contract_network_status","provider_network_contracts",["network_code","status"])
def downgrade():
 op.drop_index("ix_provider_network_contract_network_status",table_name="provider_network_contracts");op.drop_index("ix_provider_network_contracts_facility_id",table_name="provider_network_contracts");op.drop_table("provider_network_contracts")
 op.drop_index("ix_provider_network_service_network",table_name="provider_network_services") if False else None
 op.drop_index("ix_provider_network_service_network",table_name="provider_network_services");op.drop_index("ix_provider_network_services_status",table_name="provider_network_services");op.drop_index("ix_provider_network_services_facility_id",table_name="provider_network_services");op.drop_table("provider_network_services")
 op.drop_index("ix_provider_network_memberships_participation_status",table_name="provider_network_memberships");op.drop_index("ix_provider_network_memberships_network_code",table_name="provider_network_memberships");op.drop_index("ix_provider_network_memberships_facility_id",table_name="provider_network_memberships");op.drop_table("provider_network_memberships")
